### ISSUE TITLE
 The system cannot find the path specified: 'C:\Users\(my username in windows)/.local/share/languagepod101/'

### ISSUE THREAD

**Issue by yogesh1239** [nedlir/languagepod101-scraper#10]
Traceback (most recent call last):
File "D:\languagepod101-scraper-master\language101_scraper.py", line 591, in
setupLoging()
File "D:\languagepod101-scraper-master\language101_scraper.py", line 577, in setupLoging
os.mkdir(logingpath)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\Users\(my username in windows)/.local/share/languagepod101/'

i am getting this error, can you pls check if the address to download should be this?

**Comment by yogesh1239** [comment]
btw, the pdfs downloaded are corrupted, just a heads up.

**Comment by airmack** [comment]
Please see #12  
It is probably connected to your free trial account.
