### ISSUE TITLE
Tons of corrupt PDFs

### ISSUE THREAD

**Issue by Fytch** [nedlir/languagepod101-scraper#12]
Scraping japanesepod101 leaves one with many (17307 to be exact) corrupt PDF files:

![Screenshot](https://user-images.githubusercontent.com/10600373/105354423-d17f6d80-5bf0-11eb-99e4-4242e912e94d.PNG)

All these files seem to be identical: In my case, they're 41'144 bytes large and have identical checksums. They do however contain my username so it makes no sense sharing the checksums. Your sizes might consequently also be a little bit off.

Upon opening it in a text editor, I found out that these files are HTML files. Not sure why they ended up in a .pdf file.

Disclaimer: the scrape is ~5 weeks old.

**Comment by airmack** [comment]
Behavior is currently still present and therefore confirmed.

**Comment by airmack** [comment]
Hi @Fytch, 
the issue probably can't be solved. If you inspect the "faulty" pdfs you might find the following:

"Sorry, you can only download 10 PDFs during the 7-Day Trial. Please sign up for a Basic or Premium membership to access additional PDFs."

**Comment by nedlir** [comment]
This function was too buggy, it exists no more.
