### ISSUE TITLE
ERROR    'NoneType' object is not subscriptable and ERROR    Restoring download stack failed

### ISSUE THREAD

**Issue by luisae123** [nedlir/languagepod101-scraper#13]
When I run the script and get to the part where I enter my username and password and then the URL I receive this message:
root        : INFO     Sucessfully logged in via old session.
root        : ERROR    'NoneType' object is not subscriptable
root        : ERROR    Restoring download stack failed
root        : INFO     https://www.thaipod101.com/lesson-library/absolute-beginner
root        : WARNING  Could not parse https://www.thaipod101.com/lesson-library/absolute-beginner
root        : INFO     []
root        : INFO     Download stack stored
root        : INFO     Download stack stored
root        : INFO     Yatta! Finished downloading the level!

Any idea why? Thanks

**Comment by airmack** [comment]
It is probably the same problem as mentioned in #9 .
You could either try:
1. applying the diffs in the pull request "- fixed recursive directory creation"
2. use the master https://github.com/airmack/languagepod101-scraper  which already incorparetes the changes

**Comment by YahavBahat** [comment]
> It is probably the same problem as mentioned in #9 .
> You could either try:
> 
> 1. applying the diffs in the pull request "- fixed recursive directory creation"
> 2. use the master https://github.com/airmack/languagepod101-scraper  which already incorparetes the changes

Hey, I did what you suggested -  I used the master from https://github.com/airmack/languagepod101-scraper, although when I execute the script I encounter an error:

`Traceback (most recent call last):
  File "/Users/yahavbahat/Downloads/GitClone'd/languagepod101-scraper/./language101_scraper.py", line 620, in <module>
    main(args.username, args.password, args.url, args)
  File "/Users/yahavbahat/Downloads/GitClone'd/languagepod101-scraper/./language101_scraper.py", line 533, in main
    lpd.work_on_stack(stack)
  File "/Users/yahavbahat/Downloads/GitClone'd/languagepod101-scraper/./language101_scraper.py", line 479, in work_on_stack
    os.chdir(path)
FileNotFoundError: [Errno 2] No such file or directory: 'absolute-beginnerabsolute-beginner-fun-and-easy'`

I execute the script like this:

`./language101_scraper.py -u ***** -p **** --url https://www.japanesepod101.com/lesson-library/absolute-beginner`

This is the log:

https://pastebin.com/raw/37HjMsK4
