### ISSUE TITLE
Error with airmack master: No such file or directory, failing to download files and create folder structure.

### ISSUE THREAD

**Issue by YahavBahat** [nedlir/languagepod101-scraper#14]
Hi, because of an error mentioned [here](https://github.com/nedlir/languagepod101-scraper/issues/13) I used the [airmack's](https://github.com/airmack/languagepod101-scraper) master, but when I execute the script, I encounter an error:

`Traceback (most recent call last): File "/Users/****/Downloads/GitClone'd/languagepod101-scraper/./language101_scraper.py", line 620, in <module> main(args.username, args.password, args.url, args) File "/Users/****/Downloads/GitClone'd/languagepod101-scraper/./language101_scraper.py", line 533, in main lpd.work_on_stack(stack) File "/Users/****/Downloads/GitClone'd/languagepod101-scraper/./language101_scraper.py", line 479, in work_on_stack os.chdir(path) FileNotFoundError: [Errno 2] No such file or directory: 'absolute-beginnerabsolute-beginner-fun-and-easy'`

I execute the script like this:

`./language101_scraper.py -u ***** -p **** --url https://www.japanesepod101.com/lesson-library/absolute-beginner`

This is the log:

https://pastebin.com/raw/37HjMsK4

And in all the folders that it creates inside the master folder (without the normal structure of the levels), every one of them is empty.
Do you know why it happens? Thanks.

**Comment by nedlir** [comment]
Please refer to #11
