### ISSUE TITLE
Anti-botting mechanisms built into innovative sites

### ISSUE THREAD

**Issue by cyphirx** [nedlir/languagepod101-scraper#15]
It appears innovative has started putting in anti-botting protections so you may lock yourself out of your account for a time if you hammer on their systems.

**Comment by Asraelite** [comment]
Thanks for the heads up. Do you have any more details about what the limitations are exactly, so we can throttle the bot accordingly?

**Comment by nedlir** [comment]
A brief inspection of the sites shows it's not anti botting mechanism but simply a change in the site's structure.

I will commit a fix in the following days, most likely with less functionality than the current broken version

**Comment by nedlir** [comment]
Fixed with headers addition to the script.
