### ISSUE TITLE
Code Running but I can't find the downloaded files

### ISSUE THREAD

**Issue by stephensherin** [nedlir/languagepod101-scraper#21]
Hi ,

With limited coding knowledge I've been able to get the script running successfully but I can't seem to find where the files have downloaded.
The code runs and finishes with the "Yatta! Finished downloading the course" but there does not seem to be any files downloading.

Does anyone have any suggestions?

Thanks!!

**Comment by nedlir** [comment]
Hi @stephensherin.

By default, the downloads will be put in the folder you run the code.

Are you using some IDE or running directly from a folder?

**Comment by stephensherin** [comment]
Thanks for the quick reply @nedlir. I'm running it using an IDE (PyCharm). 
I believe I'm running from C:\Users\steph\PycharmProjects\CantoneseClass101. But there are no files other than the script & libraries that I originally downloaded.

**Comment by nedlir** [comment]
Try to run the file inside the folder you want the file to be downloaded into or assign another directory. you can do it straight from the commandline: `python language101_scraper.py`

For more info: [How to execute a python script in a different directory?](https://stackoverflow.com/questions/45384429/how-to-execute-a-python-script-in-a-different-directory)](https://stackoverflow.com/questions/45384429/how-to-execute-a-python-script-in-a-different-directory)
