### ISSUE TITLE
ModuleNotFoundError: No module named 'bs4'

### ISSUE THREAD

**Issue by quopquai** [nedlir/languagepod101-scraper#23]
Any idea why I get this when I try to run the script?:

line 11, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'

<img width="1032" alt="Screen Shot 2023-03-05 at 10 18 08" src="https://user-images.githubusercontent.com/88017080/222936743-c0446896-119b-463b-9b26-0561e4d19216.png">

Sorry, I'm new at this.

**Comment by nedlir** [comment]
You need to run `pip install beautifulsoup4` from your commandline.

More instructions here:
https://pypi.org/project/beautifulsoup4/

**Comment by quopquai** [comment]
thank you for your response. I installed beautifulsoup4 as per you instructions but it said "Requirement already satisfied" and when I ran the script again, it gave the same error message:

<img width="1270" alt="Screen Shot 2023-03-06 at 8 51 28" src="https://user-images.githubusercontent.com/88017080/222993200-011254af-bfff-4a07-8e3e-389e5cab29b0.png">
