### ISSUE TITLE
ModuleNotFoundError: No module named 'bs4'

### ISSUE THREAD

**Issue by quopquai** [nedlir/languagepod101-scraper#24]
thank you for your response. I installed beautifulsoup4 as per you instructions but it said "Requirement already satisfied" and when I ran the script again, it gave the same error message:

<img width="1270" alt="Screen Shot 2023-03-06 at 8 51 28" src="https://user-images.githubusercontent.com/88017080/222993200-011254af-bfff-4a07-8e3e-389e5cab29b0.png">

_Originally posted by @quopquai in https://github.com/nedlir/languagepod101-scraper/issues/23#issuecomment-1455250304_

**Comment by quopquai** [comment]
So, I figured out i need to put the "language101_scraper.py" file in the "site-packages" folder and the script started to work properly! - but then i got another error message saying,

"Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
Failed to parse the course's webpage, 'lxml' package might be missing."

Any help would be appreciated, thanks.

Do i need to subscribe to the course for this to work?

**Comment by quopquai** [comment]
I moved the py script to the 3.10/site-packages instead of the 3.9/site-packages and it finally worked!

Although, it says, "Yatta! Finished downloading the course~", nothing has actually downloaded!?!?

What am i still missing?

**Comment by nedlir** [comment]
Have you tried this solution?
https://stackoverflow.com/questions/37341614/modules-are-installed-using-pip-on-osx-but-not-found-when-importing

This seems like a problem with the system recognizing python installed libraries and not with the script.
