### ISSUE TITLE
Notice: here is a forked version that works as of December 2024

### ISSUE THREAD

**Issue by tassa-yoniso-manasi-karoto** [nedlir/languagepod101-scraper#29]
I am leaving this notice here since this repo seems inactive.

Here is a working version:
https://github.com/tassa-yoniso-manasi-karoto/languagepod101-scraper-2025

**Comment by nedlir** [comment]
@tassa-yoniso-manasi-karoto - admittedly I neglected the maintenance of this repo, can you please make a PR? I will merge.

**Comment by nedlir** [comment]
good fork, it was merged to master.
