### ISSUE TITLE
Mass scraping all lessons

### ISSUE THREAD

**Issue by Fytch** [nedlir/languagepod101-scraper#5]
Is there a way to scrape the entire lesson library? I.e. every lesson in every 'pathway' in every difficulty in here: https://www.japanesepod101.com/lesson-library/absolute-beginner

Currently it seems you have to get all the individual lesson links first.

**Comment by quique** [comment]
My fork downloads the whole lesson library for a difficulty level, just as you ask.

**Comment by Fytch** [comment]
You're right, I should have noticed that. Thank you for your work!
