### ISSUE TITLE
403 Client Error

### ISSUE THREAD

**Issue by dp247** [nedlir/languagepod101-scraper#9]
Every time I try run language101_scraper.py, I receive a 403 Client Error. I've tried passing in my login details as parameters, as well as using a configuration file. Coincidentally, I was trying to download the JPod101 Beginner library (https://www.japanesepod101.com/lesson-library/beginner) that's given as an example. 
The error received is:
    Trying to log in to https://www.japanesepod101.com
    403 Client Error: Forbidden for url: https://www.japanesepod101.com/member/login_new.php
    Could not reach site. Please check URL and internet connection.

**Comment by airmack** [comment]
Hmm ... i can't  recreate the issue. 


> 01-19 20:30 root         DEBUG    Trying to log in to https://www.japanesepod101.com
01-19 20:30 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): www.japanesepod101.com:443
01-19 20:30 urllib3.connectionpool DEBUG    https://www.japanesepod101.com:443 "POST /member/login_new.php HTTP/1.1" 302 None
01-19 20:30 urllib3.connectionpool DEBUG    https://www.japanesepod101.com:443 "GET /member/login_new.php HTTP/1.1" 200 None
01-19 20:30 root         INFO     Sucessfully logged in with new session.

Can you try to provide a **CLEAN** logfile, meaning no personal data such as passwords or username/email?
The logfile should be located in ~/.local/share/languagepod101/lp101.log

**Comment by dp247** [comment]
I ran it again today and got something totally. Log file attached. I'm currently running on Windows 10 via Powershell if that helps any - should I try on something like Ubuntu instead?
[lp101.log](https://github.com/nedlir/languagepod101-scraper/files/5842563/lp101.log)

**Comment by yogesh1239** [comment]
Traceback (most recent call last):
  File "D:\languagepod101-scraper-master\language101_scraper.py", line 591, in <module>
    setupLoging()
  File "D:\languagepod101-scraper-master\language101_scraper.py", line 577, in setupLoging
    os.mkdir(logingpath)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\(my username in windows)/.local/share/languagepod101/'

**Comment by airmack** [comment]
Seems like the downloadstack is empty.
This could either be caused by:
1. parsing errors on the website 
2. an old empty download stack.
3. some other FUP

I guess its number 2. Could you try out to run the script with the option -f (forcing a new download stack) and check the outcome?

**Comment by dp247** [comment]
Sure, I ran with the -f parameter and have attached the log file again
[lp101.log](https://github.com/nedlir/languagepod101-scraper/files/5848828/lp101.log)

**Comment by airmack** [comment]
Ok. I confirmed the issue and i know the buggy part in the code. 
Unfortunetly the logic inside of  check_for_lessons_library doesn't work and therefore the download_level function is not called. I detected some further errors in there too.
